export const words = [
    { word: "house", hint: "A familiar shell, holding countless echoes." },
    { word: "tree", hint: "A silent sentinel, rooted in stories untold." },
    { word: "water", hint: "A constant flow, shaping all it touches, yet formless itself." },
    { word: "air", hint: "An unseen breath, essential and ever-present." },
    { word: "hand", hint: "An extension of will, capable of creation or destruction." },
    { word: "eye", hint: "A window to the soul, and to the world's deceptions." },
    { word: "foot", hint: "The first step, on a journey yet unwritten." },
    { word: "stone", hint: "A timeless witness, holding moments in its core." },
    { word: "book", hint: "A silent voice, sharing worlds within its pages." },
    { word: "door", hint: "A choice, between here and the unknown beyond." },
    { word: "path", hint: "A direction taken, or one left untrod." },
    { word: "light", hint: "Reveals all, yet casts the deepest shadows." },
    { word: "dark", hint: "Where secrets dwell, and possibilities hide." },
    { word: "road", hint: "A linear journey, often with unexpected turns." },
    { word: "voice", hint: "A sound that carries truth, or conceals it." },
    { word: "time", hint: "A relentless current, flowing only forward." },
    { word: "mind", hint: "A boundless landscape, where reality is forged." },
    { word: "heart", hint: "The hidden center, beating with unseen rhythms." },
    { word: "cloud", hint: "A transient form, drifting with unseen currents." },
    { word: "sun", hint: "A distant warmth, fueling all life and its illusions." },
    { word: "moon", hint: "A silent watcher, reflecting borrowed light." },
    { word: "star", hint: "A distant fire, hinting at vast, cold spaces." },
    { word: "wind", hint: "An invisible force, shaping the unseen." },
    { word: "fire", hint: "A consuming warmth, or a dangerous spark." },
    { word: "sound", hint: "A vibration, carrying meaning or mere noise." },
    { word: "word", hint: "A vessel for thought, capable of immense power." },
    { word: "dream", hint: "A personal theater, where logic rarely applies." },
    { word: "name", hint: "A label, sometimes defining, sometimes misleading." },
    { word: "face", hint: "A mask worn daily, revealing little to the casual glance." },
    { word: "game", hint: "Rules followed or broken, with stakes often unseen." },
    { word: "story", hint: "A woven reality, where truth and fiction entwine." },
    { word: "glass", hint: "A fragile barrier, offering a distorted view." },
    { word: "mirror", hint: "A reflection, showing what is, and what might be." },
    { word: "gate", hint: "A point of passage, often guarded or locked." },
    { word: "key", hint: "A small tool, unlocking more than just doors." },
    { word: "field", hint: "An open expanse, where paths are chosen freely." },
    { word: "table", hint: "A common ground, for shared meals or weighty decisions." },
    { word: "chair", hint: "A place of rest, or of waiting." },
    { word: "clock", hint: "A silent counter, measuring moments that slip away." },
    { word: "path", hint: "A chosen direction, or one imposed by fate." },
    { word: "bridge", hint: "A connection, spanning divides." },
    { word: "wall", hint: "A boundary, built to separate or to protect." },
    { word: "window", hint: "A framed view, hinting at worlds beyond." },
    { word: "button", hint: "A small point of interaction, triggering unseen actions." },
    { word: "string", hint: "A delicate link, holding things together or apart." },
    { word: "knot", hint: "A complex tangle, or a firm bond." },
    { word: "box", hint: "A container of secrets, or just empty space." },
    { word: "cup", hint: "A vessel, holding sustenance or emptiness." },
    { word: "knife", hint: "A sharp edge, capable of creation or destruction." },
    { word: "crown", hint: "A symbol of power, sometimes a heavy burden." },
    { word: "seed", hint: "A tiny beginning, holding immense potential." },
    { word: "map", hint: "A guide, often leaving the true journey to discovery." },
    { word: "ring", hint: "A perpetual circle, with no clear beginning or end." },
    { word: "mask", hint: "A cover, hiding identity or revealing a new one." },
    { word: "thread", hint: "A fine line, connecting disparate elements." },
    { word: "tune", hint: "A sequence of notes, stirring forgotten feelings." },
    { word: "bell", hint: "A sound that calls, warns, or announces." },
    { word: "scent", hint: "An invisible trace, evoking distant memories." },
    { word: "dust", hint: "The smallest remnant, carrying histories of ages." },
    { word: "wave", hint: "A rising and falling motion, often fleeting." },
    { word: "leaf", hint: "A fragile part of a larger whole, falling to return." },
    { word: "shell", hint: "An empty vessel, once holding life or a secret." },
    { word: "root", hint: "The hidden foundation, drawing life from the unseen." },
    { word: "branch", hint: "A diverging path, extending from a common source." },
    { word: "gift", hint: "Something freely given, with unseen obligations." },
    { word: "trial", hint: "A test of endurance, or a path to revelation." },
    { word: "truth", hint: "A hidden gem, often obscured by perception." },
    { word: "lie", hint: "A carefully crafted shadow, disguising the real." },
    { word: "hope", hint: "A fragile light, persisting in the darkest corners." },
    { word: "fear", hint: "A silent master, dictating unseen actions." },
    { word: "luck", hint: "An unpredictable force, sometimes friend, sometimes foe." },
    { word: "pain", hint: "A sharp reminder, teaching unexpected lessons." },
    { word: "joy", hint: "A fleeting burst, echoing in the heart." },
    { word: "peace", hint: "A quiet stillness, hard to achieve, easy to lose." },
    { word: "war", hint: "A chaotic dance, with unforeseen consequences." },
    { word: "rest", hint: "A pause, before the next unknown journey." },
    { word: "work", hint: "Effort applied, shaping reality or oneself." },
    { word: "play", hint: "A structured freedom, with unseen rules." },
    { word: "love", hint: "A powerful bond, defying logic and reason." },
    { word: "hate", hint: "A consuming force, leaving only emptiness." },
    { word: "friend", hint: "A chosen reflection, walking beside you." },
    { word: "enemy", hint: "A challenging shadow, revealing your own limits." },
    { word: "home", hint: "A feeling more than a place, often sought." },
    { word: "travel", hint: "A movement across space, changing the perspective." },
    { word: "dream", hint: "A nocturnal journey, within the mind's own realm." },
    { word: "wake", hint: "An awakening, to a world both new and familiar." },
    { word: "sleep", hint: "A surrender to the unconscious, where thoughts drift." },
    { word: "dawn", hint: "The gentle arrival, promising new beginnings." },
    { word: "dusk", hint: "The slow departure, inviting reflection." },
    { word: "night", hint: "A canvas for stars, and for hidden fears." },
    { word: "day", hint: "A span of light, filled with unfolding events." },
    { word: "memory", hint: "A fragile fragment, constantly rewoven." },
    { word: "future", hint: "An unwritten scroll, awaiting interpretation." },
    { word: "past", hint: "A sealed book, its lessons sometimes forgotten." },
    { word: "choice", hint: "A branching point, altering all that follows." },
    { word: "chance", hint: "An unseen hand, guiding unpredictable outcomes." },
    { word: "destiny", hint: "A pre-written path, or a journey of constant choices." },
    { word: "fate", hint: "An invisible force, weaving all threads together." },
    { word: "power", hint: "A subtle influence, changing perception and reality." },
    { word: "wisdom", hint: "A quiet knowing, gained through experience and insight." },
    { word: "fool", hint: "One who sees differently, often unintentionally wise." },
    { word: "king", hint: "A heavy crown, bearing the weight of many lives." },
    { word: "queen", hint: "A silent force, often ruling from behind the scenes." },
    { word: "prince", hint: "A future hope, or a burden of expectation." },
    { word: "princess", hint: "A protected bloom, sometimes trapped, sometimes free." },
    { word: "knight", hint: "A sworn protector, battling seen and unseen foes." },
    { word: "witch", hint: "One who harnesses unseen forces, for good or ill." },
    { word: "wizard", hint: "A master of arcana, bending reality with thought." },
    { word: "hero", hint: "One who steps forward, when others turn away." },
    { word: "villain", hint: "A shadow to the hero, often driven by unseen motives." },
    { word: "ghost", hint: "A lingering presence, from a realm unseen." },
    { word: "angel", hint: "A guiding light, often appearing in times of need." },
    { word: "demon", hint: "A tempting whisper, exploiting hidden weaknesses." },
    { word: "curse", hint: "A spoken shadow, binding unseen consequences." },
    { word: "blessing", hint: "An unexpected grace, guiding unseen paths." },
    { word: "promise", hint: "A spoken bond, tying future to present." },
    { word: "secret", hint: "A hidden truth, guarded by the mind." },
    { word: "silence", hint: "A profound presence, allowing unseen thoughts to surface." },
    { word: "mystery", hint: "A puzzle without an obvious solution, inviting exploration." }
  ]